version: '3'

services:
  database: 
    container_name: vuttr-database
    image: postgres
    environment:
      POSTGRES_DB: vuttr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
  api:
    container_name: vuttr-nestjs
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:1234@database:5432/vuttr
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always
  
  